/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleBusca;
import controller.IControleBusca;
import javax.swing.JOptionPane;
import model.bean.Cliente;

/**
 *
 * @author gomes
 */
public class BuscaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscaCliente
     */
    public BuscaCliente() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label_cpfCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_rgCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_nomeCliente = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bnt_atualizarCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        label_cidadeCliente = new javax.swing.JLabel();
        label_bairroCliente = new javax.swing.JLabel();
        label_ruaCliente = new javax.swing.JLabel();
        label_numeroCliente = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_mailCliente = new javax.swing.JLabel();
        label_compleCliente = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_telCliente = new javax.swing.JLabel();
        label_tel2Cliente = new javax.swing.JLabel();
        bnt_busca = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximumSize(new java.awt.Dimension(720, 630));
        setMinimumSize(new java.awt.Dimension(720, 630));
        setName(""); // NOI18N

        jLabel1.setText("CPF");

        label_cpfCliente.setText("cpf");

        jLabel2.setText("RG");

        label_rgCliente.setText("rg");

        jLabel3.setText("NOME");

        label_nomeCliente.setText("nome");

        jButton1.setText("DELETAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bnt_atualizarCliente.setText("ATUALIZAR");
        bnt_atualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_atualizarClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("ENDEREÇO");

        label_cidadeCliente.setText("cidade");

        label_bairroCliente.setText("bairro");

        label_ruaCliente.setText("rua");

        label_numeroCliente.setText("numero");

        jLabel9.setText("EMAIL");

        label_mailCliente.setText("email");

        label_compleCliente.setText("complemento");

        jLabel12.setText("TELEFONE");

        label_telCliente.setText("telefone1");

        label_tel2Cliente.setText("telefone2");

        bnt_busca.setText("Nova Busca");
        bnt_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_buscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(label_telCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_tel2Cliente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 312, Short.MAX_VALUE)
                                        .addComponent(bnt_busca)))))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_mailCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_ruaCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label_numeroCliente))
                                    .addComponent(jButton1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(label_bairroCliente))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(label_compleCliente))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(155, 155, 155)
                                        .addComponent(bnt_atualizarCliente))))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)
                                .addComponent(label_nomeCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_cpfCliente)
                                    .addComponent(jLabel4)
                                    .addComponent(label_rgCliente))
                                .addGap(37, 37, 37)
                                .addComponent(label_cidadeCliente)))
                        .addContainerGap(338, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_cpfCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(label_rgCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(label_nomeCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(label_cidadeCliente)
                    .addComponent(label_bairroCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ruaCliente)
                    .addComponent(label_numeroCliente)
                    .addComponent(label_compleCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(label_mailCliente))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(label_telCliente)
                    .addComponent(label_tel2Cliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(bnt_atualizarCliente)
                    .addComponent(bnt_busca))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bnt_atualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_atualizarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_atualizarClienteActionPerformed

    private void bnt_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_buscaActionPerformed
        String cpfCliente = JOptionPane.showInputDialog("Digite o cpf");

        IControleBusca controle = new ControleBusca();
        Cliente client = controle.ClienteBuscaCpf(cpfCliente);
        if (!client.equals(null)) {

            this.label_cpfCliente.setText(client.getCpf());
            this.label_rgCliente.setText(client.getRg());
            this.label_nomeCliente.setText(client.getNome());
            this.label_cidadeCliente.setText(client.getCidade());
            this.label_bairroCliente.setText(client.getBairro());
            this.label_ruaCliente.setText(client.getRua());
            this.label_nomeCliente.setText(client.getNome());
            this.label_numeroCliente.setText("" + client.getNumero());
            this.label_compleCliente.setText(client.getComplemento());
            this.label_nomeCliente.setText(client.getEmail());
            this.label_telCliente.setText(client.getTelefone1());
            this.label_tel2Cliente.setText(client.getTelefone2());
        } else { 
            JOptionPane.showMessageDialog(null, "Tente novamente");
        }
    }//GEN-LAST:event_bnt_buscaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_atualizarCliente;
    private javax.swing.JButton bnt_busca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel label_bairroCliente;
    public javax.swing.JLabel label_cidadeCliente;
    public javax.swing.JLabel label_compleCliente;
    public javax.swing.JLabel label_cpfCliente;
    public javax.swing.JLabel label_mailCliente;
    public javax.swing.JLabel label_nomeCliente;
    public javax.swing.JLabel label_numeroCliente;
    public javax.swing.JLabel label_rgCliente;
    public javax.swing.JLabel label_ruaCliente;
    public javax.swing.JLabel label_tel2Cliente;
    public javax.swing.JLabel label_telCliente;
    // End of variables declaration//GEN-END:variables
}
