/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleBusca;
import controller.ControleCadastro;
import controller.IControleBusca;
import controller.IControleCadastro;
import javax.swing.JOptionPane;
import model.bean.Cliente;

/**
 *
 * @author gomes
 */
public class BuscaDiretaAtualizarCliente extends javax.swing.JInternalFrame {
    private String tipo;
    public BuscaDiretaAtualizarCliente(String tipo) {
        initComponents();
        this.tipo = tipo;
        if(!(tipo.equals("GERENTE") || tipo.equals("gerente") || tipo.equals("Gerente"))){
            this.bnt_atualizarCliente.setSelected(false);
            this.campo_nome.setEditable(false);
            this.campo_cidade.setEditable(false);
            this.campo_bairro.setEditable(false);
            this.campo_rua.setEditable(false);
            this.campo_numero.setEditable(false);
            this.campo_complemento.setEditable(false);
            this.campo_email.setEditable(false);
            this.campo_telefone1.setEditable(false);
            this.campo_telefone2.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label_cpfCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_rgCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_nomeCliente = new javax.swing.JLabel();
        bnt_atualizarCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        label_cidadeCliente = new javax.swing.JLabel();
        label_bairroCliente = new javax.swing.JLabel();
        label_ruaCliente = new javax.swing.JLabel();
        label_numeroCliente = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_mailCliente = new javax.swing.JLabel();
        label_compleCliente = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_telCliente = new javax.swing.JLabel();
        label_tel2Cliente = new javax.swing.JLabel();
        bnt_busca = new javax.swing.JButton();
        campo_nome = new javax.swing.JTextField();
        campo_cidade = new javax.swing.JTextField();
        campo_bairro = new javax.swing.JTextField();
        campo_rua = new javax.swing.JTextField();
        campo_numero = new javax.swing.JTextField();
        campo_complemento = new javax.swing.JTextField();
        campo_email = new javax.swing.JTextField();
        campo_telefone1 = new javax.swing.JTextField();
        campo_telefone2 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel1.setText("CPF");

        label_cpfCliente.setText("cpf");

        jLabel2.setText("RG");

        label_rgCliente.setText("rg");

        jLabel3.setText("NOME");

        label_nomeCliente.setText("nome");

        bnt_atualizarCliente.setText("ATUALIZAR");
        bnt_atualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_atualizarClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("ENDEREÇO");

        label_cidadeCliente.setText("cidade");

        label_bairroCliente.setText("bairro");

        label_ruaCliente.setText("rua");

        label_numeroCliente.setText("numero");

        jLabel9.setText("EMAIL");

        label_mailCliente.setText("email");

        label_compleCliente.setText("complemento");

        jLabel12.setText("TELEFONE");

        label_telCliente.setText("telefone1");

        label_tel2Cliente.setText("telefone2");

        bnt_busca.setText("Nova Busca");
        bnt_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_buscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(label_nomeCliente)
                                        .addComponent(campo_nome)
                                        .addComponent(campo_cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
                                    .addComponent(label_bairroCliente)
                                    .addComponent(label_ruaCliente)
                                    .addComponent(campo_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_numeroCliente)
                                    .addComponent(campo_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_compleCliente)
                                    .addComponent(campo_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_mailCliente)
                                    .addComponent(campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(label_cidadeCliente)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(label_cpfCliente))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(30, 30, 30)
                                    .addComponent(label_rgCliente)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_tel2Cliente)
                                    .addComponent(label_telCliente)))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(bnt_atualizarCliente)
                .addGap(168, 168, 168)
                .addComponent(bnt_busca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cpfCliente)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_rgCliente)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(label_nomeCliente))
                        .addGap(2, 2, 2)
                        .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(label_cidadeCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_bairroCliente)
                        .addGap(8, 8, 8)
                        .addComponent(campo_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(label_ruaCliente)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(campo_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(label_numeroCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_compleCliente)
                .addGap(2, 2, 2)
                .addComponent(campo_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(label_mailCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(label_telCliente)
                    .addComponent(campo_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tel2Cliente)
                    .addComponent(campo_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_atualizarCliente)
                    .addComponent(bnt_busca))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_atualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_atualizarClienteActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Quer atualizar os dados desse Cliente?", "Confiarmar", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            IControleCadastro i = new ControleCadastro();
            long g;
            try {
                g = Long.parseLong(this.campo_numero.getText());
            } catch (Exception e) {
                g = 0;
            }
            i.AtualizarCliente(this.campo_nome.getText(),this.label_cpfCliente.getText(), this.label_rgCliente.getText(),
                    this.campo_telefone1.getText(), this.campo_telefone2.getText(),
                    this.campo_email.getText(), this.campo_cidade.getText(), this.campo_rua.getText(),
                    this.campo_bairro.getText(), this.campo_complemento.getText(), g);
            
          //  String nome, String cpf, String rg, String telefone1, String telefone2, 
        //String email, String cidade, String rua, String bairro, String complemento, long numero
        }
    }//GEN-LAST:event_bnt_atualizarClienteActionPerformed

    private void bnt_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_buscaActionPerformed
        String cpfCliente = JOptionPane.showInputDialog("Digite o cpf");

        IControleBusca controle = new ControleBusca();
        Cliente client = controle.ClienteBuscaCpf(cpfCliente);
        try{
            this.label_cpfCliente.setText(client.getCpf());
            this.label_rgCliente.setText(client.getRg());
            this.label_nomeCliente.setText(client.getNome());
            this.label_cidadeCliente.setText(client.getCidade());
            this.label_bairroCliente.setText(client.getBairro());
            this.label_ruaCliente.setText(client.getRua());
            this.label_nomeCliente.setText(client.getNome());
            this.label_numeroCliente.setText("" + client.getNumero());
            this.label_compleCliente.setText(client.getComplemento());
            this.label_nomeCliente.setText(client.getEmail());
            this.label_telCliente.setText(client.getTelefone1());
            this.label_tel2Cliente.setText(client.getTelefone2());
        }catch(Exception e) { 
            JOptionPane.showMessageDialog(null, "Tente novamente");
        }
    }//GEN-LAST:event_bnt_buscaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_atualizarCliente;
    private javax.swing.JButton bnt_busca;
    private javax.swing.JTextField campo_bairro;
    private javax.swing.JTextField campo_cidade;
    private javax.swing.JTextField campo_complemento;
    private javax.swing.JTextField campo_email;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_numero;
    private javax.swing.JTextField campo_rua;
    private javax.swing.JTextField campo_telefone1;
    private javax.swing.JTextField campo_telefone2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel label_bairroCliente;
    public javax.swing.JLabel label_cidadeCliente;
    public javax.swing.JLabel label_compleCliente;
    public javax.swing.JLabel label_cpfCliente;
    public javax.swing.JLabel label_mailCliente;
    public javax.swing.JLabel label_nomeCliente;
    public javax.swing.JLabel label_numeroCliente;
    public javax.swing.JLabel label_rgCliente;
    public javax.swing.JLabel label_ruaCliente;
    public javax.swing.JLabel label_tel2Cliente;
    public javax.swing.JLabel label_telCliente;
    // End of variables declaration//GEN-END:variables
}
