/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleBusca;
import controller.ControleDeListagem;
import controller.IControleBusca;
import controller.IControleListagem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Produto;
import java.util.ArrayList;

/**
 *
 * @author antonio
 */
public class ListarEstoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarEstoque
     */
    public ListarEstoque() {
        initComponents();
        setClosable(true);
        setIconifiable(true);
        this.read();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        campoBusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        nome = new javax.swing.JRadioButton();
        codigo = new javax.swing.JRadioButton();

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade", "Tempo Garantia(meses)", "Descrição ", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(nome);
        nome.setText("Pesquisar por nome");

        buttonGroup1.add(codigo);
        codigo.setText("pesquisar por codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codigo)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!(this.nome.isSelected()) && !(this.codigo.isSelected())){
            JOptionPane.showMessageDialog(null, "Selecione uma maneira de pesquisar!");
            this.read();
            
        }else if(this.nome.isSelected()){
            DefaultTableModel modelo = (DefaultTableModel) this.tabela.getModel();
            modelo.setNumRows(0); //eliminar duplicadas do java 
            IControleBusca i = new ControleBusca();
            ArrayList<Produto> prod = i.buscaProdutoNome(this.campoBusca.getText());
            if (prod.size() >= 1){
                for (Produto p:prod){ //atribuir um obbjeto já que vamos percorer o objeto
                    modelo.addRow(new Object[]{
                        p.getCodigo(),
                        p.getNome(),
                        p.getQt_disponiveis(),
                        p.getTempo_garantia(),
                        p.getDescicao(),
                        p.getPrecoUnitario()
                    });
                 }
            }else{
                JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                this.read();
            }
            
        }else if (this.codigo.isSelected()){
            DefaultTableModel modelo = (DefaultTableModel) this.tabela.getModel();
            modelo.setNumRows(0); //eliminar duplicadas do java 
            IControleBusca i2 = new ControleBusca();
            Produto prod = i2.buscaProdutocodigo(this.campoBusca.getText());
            if (prod != null){
                modelo.addRow(new Object[]{
                      prod.getCodigo(),
                      prod.getNome(),
                      prod.getQt_disponiveis(),
                      prod.getTempo_garantia(),
                      prod.getDescicao(),
                      prod.getPrecoUnitario()
                });
            }else{
                JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                this.read();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void read(){
        DefaultTableModel modelo = (DefaultTableModel) this.tabela.getModel();
        modelo.setNumRows(0); //eliminar duplicadas do java 
        IControleListagem i = new ControleDeListagem();
        for (Produto p: i.Produtos()){ //atribuir um obbjeto já que vamos percorer o objeto
            if (p.getQt_disponiveis() >0){//garantindo que somente o estoque será mostrado e não produtos com 0 de qtd
                modelo.addRow(new Object[]{
                    p.getCodigo(),
                    p.getNome(),
                    p.getQt_disponiveis(),
                    p.getTempo_garantia(),
                    p.getDescicao(),
                    p.getPrecoUnitario()
                });
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JRadioButton codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton nome;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
