/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.*;
import javax.swing.ImageIcon;

/**
 *
 * @author julio
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    public TelaCliente() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titulo = new javax.swing.JLabel();
        label_cpf = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        rg = new javax.swing.JTextField();
        label_cpf10 = new javax.swing.JLabel();
        label_cpf11 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        label_cpf13 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        label_cpf14 = new javax.swing.JLabel();
        telefone1 = new javax.swing.JTextField();
        label_cpf15 = new javax.swing.JLabel();
        telefone2 = new javax.swing.JTextField();
        label_cpf16 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        label_cpf17 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        label_cpf18 = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        label_cpf19 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        label_cpf21 = new javax.swing.JLabel();
        complemento = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastrar Cliente");
        setPreferredSize(new java.awt.Dimension(674, 555));

        label_titulo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        label_titulo.setText("Registrar Clientes");
        label_titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        label_cpf.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        label_cpf.setText("CPF");

        label_cpf10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        label_cpf10.setText("RG");

        label_cpf11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        label_cpf11.setText("NOME");

        label_cpf13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        label_cpf13.setText("EMAIL");

        label_cpf14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        label_cpf14.setText("TEL");

        label_cpf15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        label_cpf15.setText("TEL 2");

        label_cpf16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        label_cpf16.setText("RUA");

        label_cpf17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        label_cpf17.setText("CIDADE");

        label_cpf18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        label_cpf18.setText("BAIRRO");

        rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaActionPerformed(evt);
            }
        });

        label_cpf19.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        label_cpf19.setText("NUMERO");

        label_cpf21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        label_cpf21.setText("COMPLEMENTO");

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_cpf13)
                                    .addComponent(label_cpf14)
                                    .addComponent(label_cpf17))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label_cpf16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rua))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label_cpf15)
                                        .addGap(2, 2, 2)
                                        .addComponent(telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_cpf10)
                                .addGap(39, 39, 39)
                                .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label_cpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_cpf11)
                                .addGap(18, 18, 18)
                                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_titulo)
                        .addGap(242, 242, 242))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_cpf21)
                        .addGap(18, 18, 18)
                        .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_cpf18)
                        .addGap(18, 18, 18)
                        .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_cpf19)
                        .addGap(18, 18, 18)
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cpf11))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cpf10)
                    .addComponent(label_cpf)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cpf13)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cpf14)
                    .addComponent(telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cpf15)
                    .addComponent(telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cpf17)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cpf16)
                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cpf18)
                    .addComponent(label_cpf19)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cpf21)
                    .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 640, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
       //RESOLVER O PROBLEMA DO mysql permitir campos '' e não os considerar como null
        IControleCadastro c = new ControleCadastro(); //instanciar o controlador de cadastro
        String d = this.numero.getText(); //receber o numero para transformar em int
        long num;
        if (d.equals("")){ //se não for fonecido um numero para casa setar como 0
            num = 0;
        }else{
            num = Long.parseLong(this.numero.getText()); //coloacr na variavel num o valor da casa
        }
        //chamar a função de cadastrar cliente
        c.CadastrarCliente(this.nome.getText(), this.cpf.getText(), this.rg.getText(), this.telefone1.getText(), this.telefone2.getText(), this.email.getText(), this.cidade.getText(), this.rua.getText(), this.bairro.getText(), this.complemento.getText(), num);
        //limpar os campos apos a edição
        this.nome.setText(""); this.cpf.setText(""); this.rg.setText(""); this.telefone1.setText("");
        this.telefone2.setText(""); this.email.setText(""); this.cidade.setText("");this.email.setText(""); this.cidade.setText(""); this.rua.setText(""); this.bairro.setText(""); this.complemento.setText("");
        this.numero.setText("");
        
    }//GEN-LAST:event_CadastrarActionPerformed

    private void ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField complemento;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JLabel label_cpf;
    private javax.swing.JLabel label_cpf10;
    private javax.swing.JLabel label_cpf11;
    private javax.swing.JLabel label_cpf13;
    private javax.swing.JLabel label_cpf14;
    private javax.swing.JLabel label_cpf15;
    private javax.swing.JLabel label_cpf16;
    private javax.swing.JLabel label_cpf17;
    private javax.swing.JLabel label_cpf18;
    private javax.swing.JLabel label_cpf19;
    private javax.swing.JLabel label_cpf21;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField rg;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField telefone1;
    private javax.swing.JTextField telefone2;
    // End of variables declaration//GEN-END:variables
}
